export const ENTRY_ADDED = 'ENTRY_ADDED';
export const ENTRY_REMOVED = 'ENTRY_REMOVED';
export const ENTRY_EDIT_STARTED = 'ENTRY_EDIT_STARTED';
export const ENTRY_EDIT_FINISHED = 'ENTRY_EDIT_FINISHED';
export const TABLE_SORT_CHANGED = 'TABLE_SORT_CHANGED';
export const SEARCH_STARTED = 'SEARCH_STARTED';
export const SEARCH_COMPLETED = 'SEARCH_COMPLETED';
